---
- name: SETUP K8S DATA-PLANE COMPONENTS FOR MASTERS.
  hosts: masters
  tasks:
    - name: SETUP COMPONENTS.
      block:
        - name: SETUP K8S DATA-PLANE COMPONENTS.
          import_role:
            name: k8s
            tasks_from: k8s-control-plane-components.yaml
          when: master_scheduled | bool
          tags:
            - data_plane
