---
- name: SETUP BASIC SYSTEM.
  hosts: all
  tasks:
    - name: SETUP COMPONENTS.
      block:
        - name: INSTALL BASIC COMPONENTS.
          import_role:
            name: packages
            tasks_from: update-repo.yaml
          tags:
            - basic

        - name: INSTALL BASIC COMPONENTS.
          import_role:
            name: packages
            tasks_from: basic.yaml
          tags:
            - basic_pkg

        - name: INSTALL BASIC COMPONENTS.
          import_role:
            name: k8s
            tasks_from: k8s-basic.yaml
          tags:
            - basic_pkg

        - name: SETUP BASIC NETWORK.
          import_role:
            name: network
            tasks_from: basic.yaml
          tags:
            - basic_network

        - name: SETUP BASIC CRI.
          import_role:
            name: k8s
            tasks_from: k8s-containerd-runtime.yaml
          when: basic_cri == "containerd"
          tags:
            - basic_cri

        - name: SETUP BASIC CNI.
          import_role:
            name: k8s
            tasks_from: k8s-cni-basic.yaml
          tags:
            - basic_cni

        - name: SETUP BASIC KUBELET.
          import_role:
            name: k8s
            tasks_from: k8s-kubelet-service.yaml
          when: setup_cluster_type == "static-pod"
          tags:
            - kubelet_service

        - name: pull an image
          shell:
            ctr image pull {{ component_image }}
          loop:
            - k8s.gcr.io/etcd:3.5.3-0
            - k8s.gcr.io/kube-apiserver:v1.23.5
          loop_control:
            loop_var: component_image
          tags:
            - pull