---
- name: DOWNLOAD BASIC TAR K8S-CP-COMPONENTS.
  ansible.builtin.unarchive:
    src: "{{ k8s_cp_tar.url }}"
    dest: "{{ k8s_cp_tar.path }}"
    remote_src: yes
  loop:
    - url: https://github.com/etcd-io/etcd/releases/download/v{{ etcd_version }}/etcd-v{{ etcd_version }}-linux-amd64.tar.gz
      path: /root
  loop_control:
      loop_var: k8s_cp_tar

- name: NEW <{{ component }}> CA.
  vars:
    component: etcd
  block:
    - name: CREATE <{{ component }}> CA.
      vars:
        csr:
          CN: etcd-ca
          names:
            - O: "etcd-ca"
      import_role:
        name: k8s
        tasks_from: k8s-certificates-ca-create.yaml
      delegate_to: "{{ groups.masters[0] }}"

    - name: DELIVERY CA.
      import_role:
        name: k8s
        tasks_from: k8s-certificates-ca-delivery.yaml

- name: CREATE CERT ETCD SERVER.
  vars:
    hosts_list: 
      - "127.0.0.1"
      - "localhost"
      - "{{ ansible_default_ipv4.address }}"
    csr:
      CN: "system:etcd-peer"
      names:
        - O: "system:etcd"
      hosts: "{{ hosts_list + groups.masters }}"
    profile: peer
    ca: etcd
  import_role:
    name: k8s
    tasks_from: k8s-certificate-template.yaml
  tags:
    - etcd_ssl

- name: CREATE A REMOTE FILE WITH FOUND CONTENT. 
  ansible.builtin.copy:
    src: /root/etcd-v{{ etcd_version }}-linux-amd64/{{item}}
    dest: /usr/bin/{{ item }}
    remote_src: true
    mode: 0775
  loop:
    - etcd
    - etcdctl
    - etcdutl

- name: ADD NEW SERVICES.
  vars:
    services_list:
      - etcd.service
  import_role:
    name: k8s
    tasks_from: k8s-service-create.yaml
  when: master_scheduled | bool
  tags:
    - etcd_service_update