- name: NEW <{{ component }}> CA.
  vars:
    component: "{{ (component_local | default(k8s_component)) | default('root') }}"
  block:
    - name: CREATE <{{ component }}> CA.
      vars:
        csr:
          CN: "{{ component }}-ca"
          names:
            - O: "{{ component }}-ca"
              OU: Terra-kube
      import_role:
        name: k8s
        tasks_from: k8s-certificates-ca-create.yaml
      delegate_to: "{{ groups.masters[0] }}"

    - name: DELIVERY CA.
      import_role:
        name: k8s
        tasks_from: k8s-certificates-ca-delivery.yaml
