- name: BASIC SETUP.
  vars:
    ca_new: true
  import_role:
    name: k8s
    tasks_from: k8s-basic.yaml
  tags:
    - basic

- name: CREATE NEW CA <{{ component_local }}>.
  vars:
    ca_new: true
  import_role:
    name: k8s
    tasks_from: k8s-certificates-ca-new.yaml
  tags:
    - create_root_ca

- name: SETUP KUBELET.
  import_role:
    name: k8s
    tasks_from: k8s-kubelet.yaml
  tags:
    - kubelet

- name: SETUP ETCD CLUSTER.
  import_role:
    name: k8s
    tasks_from: k8s-etcd.yaml
  tags:
    - etcd

- name: SETUP KUBE-APISERVER.
  import_role:
    name: k8s
    tasks_from: k8s-kube-apiserver.yaml
  tags:
    - kube_apiserver

- name: SETUP KUBE-CONTROLLER-MANAGER.
  import_role:
    name: k8s
    tasks_from: k8s-kube-controller-manager.yaml
  tags:
    - kube_controller_manager

- name: SETUP KUBE-SCHEDULER.
  import_role:
    name: k8s
    tasks_from: k8s-kube-scheduler.yaml
  tags:
    - kube_scheduler

- name: SETUP KUBEADM.
  import_role:
    name: k8s
    tasks_from: k8s-kubeadm.yaml
  tags:
    - kubeadm

