- name: BLCOK SERVICES.
  block:
    - name: COPY SERVICES.
      ansible.builtin.template:
        src: "services/{{ service_name }}"
        dest: "{{ default_path_systemd }}/{{ service_name }}"
        owner: root
        group: root
        mode: '0775'
      loop: "{{ services_list }}"
      loop_control:
          loop_var: service_name
      register: service_status

    - name: RESTART SERVICES IF CHANGED.
      block:
        - name: DAEMON-RELOAD.
          ansible.builtin.systemd:
            daemon_reload: yes

        - name: RESTART SERVICE <{{ k8s_component }}>.
          vars:
            list_k8s_components:
              - kube-apiserver
              - kube-controller-manager
              - kube-scheduler
              - etcd
            service_enabled: | 
              {%- if setup_cluster_type == 'service' -%}
              true
              {%- elif serive_changed.service_name not in list_k8s_components  -%}
              true
              {%- else -%}
              false
              {%- endif -%}
            service_state: |-
              {%- if setup_cluster_type == 'service' -%}
              restarted
              {%- elif serive_changed.service_name not in list_k8s_components  -%}
              restarted
              {%- else -%}
              stopped
              {%- endif -%}
          service:
            name: "{{ serive_changed.service_name }}"
            state: "{{ service_state.strip(' ') }}"
            enabled: "{{ service_enabled | bool }}"
          loop: "{{ service_status.results }}"
          loop_control:
              loop_var: serive_changed

      when: service_status.changed | bool or 
            service_state is defined
  tags:
    - update_services
