kubelet_args:
  - --container-runtime=remote 
  - --container-runtime-endpoint=/run/containerd/containerd.sock
  - --pod-infra-container-image=k8s.gcr.io/pause:3.6
  - --root-dir=/var/lib/kubelet 
  - --cni-bin-dir=/opt/cni/bin 
  - --cni-conf-dir=/etc/cni/net.d 
  - --network-plugin=cni 
  - --register-node=true
  - --image-pull-progress-deadline=2m
  - --v=2
  - --bootstrap-kubeconfig={{ default_path_kubernetes }}/kubelet/bootstrap-kubeconfig
  - --cert-dir={{ default_path_pki_certs }}/kubelet
  - --rotate-certificates=true
  - --anonymous-auth="false"

kubelet_config: |
  apiVersion: kubelet.config.k8s.io/v1beta1
  authentication:
    anonymous:
      enabled: false
    webhook:
      cacheTTL: 0s
      enabled: true
    x509:
      clientCAFile: "{{ default_path_pki_ca }}/root-ca.pem"
  authorization:
    mode: Webhook
    webhook:
      cacheAuthorizedTTL: 0s
      cacheUnauthorizedTTL: 0s
  cgroupDriver: systemd
  clusterDNS:
    - "{{ internal_dns_ip }}"
  clusterDomain: cluster.local
  cpuManagerReconcilePeriod: 0s
  evictionPressureTransitionPeriod: 0s
  fileCheckFrequency: 0s
  healthzBindAddress: 127.0.0.1
  healthzPort: 10248
  httpCheckFrequency: 0s
  imageMinimumGCAge: 0s
  kind: KubeletConfiguration
  logging:
    flushFrequency: 0
    options:
      json:
        infoBufferSize: "0"
    verbosity: 0
  memorySwap: {}
  nodeStatusReportFrequency: 0s
  nodeStatusUpdateFrequency: 0s
  resolvConf: /run/systemd/resolve/resolv.conf
  rotateCertificates: true
  runtimeRequestTimeout: 0s
  serverTLSBootstrap: true
  shutdownGracePeriod: 0s
  shutdownGracePeriodCriticalPods: 0s
  staticPodPath: "{{ default_path_static_pod }}"
  streamingConnectionIdleTimeout: 0s
  syncFrequency: 0s
  volumeStatsAggPeriod: 0s