k8s_version_major:    "{{ '.'.join(k8s_version.split('.')[0:1]) }}"
k8s_version:          "1.23.5"
containerd_version:   "1.6.2"
cni_plugin:           "1.1.1"
runc_version:         "1.0.0-rc93"
cri_tool_version:     "1.23.0"
cfssl_version:        "1.6.1"
basic_cri:            "containerd"
arch:                 "amd64"    

kubernetes_release_bin_path: https://storage.googleapis.com/kubernetes-release/release
kubernetes_release_image_path: k8s.gcr.io

build:
  etcd:
    bin: 
      path: https://github.com/etcd-io/etcd/releases/download/
      version: "3.5.4"
    image: 
      path: "{{ kubernetes_release_image_path }}/etcd"
      version: 3.5.3-0

  kube-apiserver:
    bin: 
      path: "{{ kubernetes_release_bin_path }}"
      version: "{{ k8s_version }}"
    image: 
      path: "{{ kubernetes_release_image_path }}/kube-apiserver"
      version: v{{ k8s_version }}

  kube-controller-manager:
    bin: 
      path: "{{ kubernetes_release_bin_path }}"
      version: "{{ k8s_version }}"
    image: 
      path: "{{ kubernetes_release_image_path }}/kube-controller-manager"
      version: v{{ k8s_version }}

  kube-scheduler:
    bin: 
      path: "{{ kubernetes_release_bin_path }}"
      version: "{{ k8s_version }}"
    image: 
      path: "{{ kubernetes_release_image_path }}/kube-scheduler"
      version: v{{ k8s_version }}

  kubelet:
    bin: 
      path: "{{ kubernetes_release_bin_path }}"
      version: "{{ k8s_version }}"

  kubeadm:
    bin: 
      path: "{{ kubernetes_release_bin_path }}"
      version: "{{ k8s_version }}"