---
apiVersion: v1
clusters:
- cluster:
    certificate-authority: /etc/kubernetes/pki/ca/root-ca.pem
    server: https://127.0.0.1:6443
  name: kubernetes
contexts:
- context:
    cluster: kubernetes
    namespace: default
    user: system:kube-apiserver
  name: system:kube-apiserver@kubernetes
current-context: system:kube-apiserver@kubernetes
kind: Config
preferences: {}
users:
- name: system:kube-apiserver
  user:
    client-certificate: /etc/kubernetes/pki/certs/kube-apiserver/system:kube-apiserver-kubelet-client.pem
    client-key: /etc/kubernetes/pki/certs/kube-apiserver/system:kube-apiserver-kubelet-client-key.pem