resource "vault_pki_secret_backend_role" "kubernetes-role" {
    depends_on = [vault_mount.intermediate]
    
    for_each                            = "${local.kubernetes_issuers_content_map}"
    
    backend                             = "${local.ssl.intermediate["kubernetes"].path}"
    name                                = "${each.key}"

    allow_any_name                      = "${each.value.value.allow_any_name}"
    allow_bare_domains                  = "${each.value.value.allow_bare_domains}"
    allow_glob_domains                  = "${each.value.value.allow_glob_domains}"
    allow_ip_sans                       = "${each.value.value.allow_ip_sans}"
    allow_localhost                     = "${each.value.value.allow_localhost}"
    allow_subdomains                    = "${each.value.value.allow_subdomains}"
    allowed_domains_template            = "${each.value.value.allowed_domains_template}"
    allowed_domains                     = "${each.value.value.allowed_domains}"
    allowed_other_sans                  = "${each.value.value.allowed_other_sans}"
    allowed_serial_numbers              = "${each.value.value.allowed_serial_numbers}"
    allowed_uri_sans                    = "${each.value.value.allowed_uri_sans}"
    basic_constraints_valid_for_non_ca  = "${each.value.value.basic_constraints_valid_for_non_ca}"
    client_flag                         = "${each.value.value.client_flag}"
    server_flag                         = "${each.value.value.server_flag}"
    code_signing_flag                   = "${each.value.value.code_signing_flag}"
    email_protection_flag               = "${each.value.value.email_protection_flag}"
    enforce_hostnames                   = "${each.value.value.enforce_hostnames}"
    generate_lease                      = "${each.value.value.generate_lease}"
    key_bits                            = "${each.value.value.key_bits}"
    key_type                            = "${each.value.value.key_type}"
    key_usage                           = "${each.value.value.key_usage}"
    ext_key_usage                       = "${each.value.value.ext_key_usage}"
    no_store                            = "${each.value.value.no_store}"
    require_cn                          = "${each.value.value.require_cn}"
    ttl                                 = "${each.value.value.ttl}"
    use_csr_common_name                 = "${each.value.value.use_csr_common_name}"
    organization                        = "${each.value.value.organization}"
    country                             = "${each.value.value.country}"
    locality                            = "${each.value.value.locality}"
    ou                                  = "${each.value.value.ou}"
    postal_code                         = "${each.value.value.postal_code}"
    province                            = "${each.value.value.province}"
    street_address                      = "${each.value.value.street_address}"
}
resource "vault_pki_secret_backend_role" "etcd-role" {
    depends_on = [vault_mount.intermediate]
    
    for_each                            = "${local.etcd_issuers_content_map}"
    
    backend                             = "${local.ssl.intermediate["etcd"].path}"
    name                                = "${each.key}"

    allow_any_name                      = "${each.value.value.allow_any_name}"
    allow_bare_domains                  = "${each.value.value.allow_bare_domains}"
    allow_glob_domains                  = "${each.value.value.allow_glob_domains}"
    allow_ip_sans                       = "${each.value.value.allow_ip_sans}"
    allow_localhost                     = "${each.value.value.allow_localhost}"
    allow_subdomains                    = "${each.value.value.allow_subdomains}"
    allowed_domains_template            = "${each.value.value.allowed_domains_template}"
    allowed_domains                     = "${each.value.value.allowed_domains}"
    allowed_other_sans                  = "${each.value.value.allowed_other_sans}"
    allowed_serial_numbers              = "${each.value.value.allowed_serial_numbers}"
    allowed_uri_sans                    = "${each.value.value.allowed_uri_sans}"
    basic_constraints_valid_for_non_ca  = "${each.value.value.basic_constraints_valid_for_non_ca}"
    client_flag                         = "${each.value.value.client_flag}"
    server_flag                         = "${each.value.value.server_flag}"
    code_signing_flag                   = "${each.value.value.code_signing_flag}"
    email_protection_flag               = "${each.value.value.email_protection_flag}"
    enforce_hostnames                   = "${each.value.value.enforce_hostnames}"
    generate_lease                      = "${each.value.value.generate_lease}"
    key_bits                            = "${each.value.value.key_bits}"
    key_type                            = "${each.value.value.key_type}"
    key_usage                           = "${each.value.value.key_usage}"
    ext_key_usage                       = "${each.value.value.ext_key_usage}"
    no_store                            = "${each.value.value.no_store}"
    require_cn                          = "${each.value.value.require_cn}"
    ttl                                 = "${each.value.value.ttl}"
    use_csr_common_name                 = "${each.value.value.use_csr_common_name}"
    organization                        = "${each.value.value.organization}"
    country                             = "${each.value.value.country}"
    locality                            = "${each.value.value.locality}"
    ou                                  = "${each.value.value.ou}"
    postal_code                         = "${each.value.value.postal_code}"
    province                            = "${each.value.value.province}"
    street_address                      = "${each.value.value.street_address}"
}

resource "vault_pki_secret_backend_role" "front-proxy-role" {
    depends_on = [vault_mount.intermediate]
    
    for_each                            = "${local.front_proxy_issuers_content_map}"
    backend                             = "${local.ssl.intermediate["front-proxy"].path}"
    name                                = "${each.key}"

    allow_any_name                      = "${each.value.value.allow_any_name}"
    allow_bare_domains                  = "${each.value.value.allow_bare_domains}"
    allow_glob_domains                  = "${each.value.value.allow_glob_domains}"
    allow_ip_sans                       = "${each.value.value.allow_ip_sans}"
    allow_localhost                     = "${each.value.value.allow_localhost}"
    allow_subdomains                    = "${each.value.value.allow_subdomains}"
    allowed_domains_template            = "${each.value.value.allowed_domains_template}"
    allowed_domains                     = "${each.value.value.allowed_domains}"
    allowed_other_sans                  = "${each.value.value.allowed_other_sans}"
    allowed_serial_numbers              = "${each.value.value.allowed_serial_numbers}"
    allowed_uri_sans                    = "${each.value.value.allowed_uri_sans}"
    basic_constraints_valid_for_non_ca  = "${each.value.value.basic_constraints_valid_for_non_ca}"
    client_flag                         = "${each.value.value.client_flag}"
    server_flag                         = "${each.value.value.server_flag}"
    code_signing_flag                   = "${each.value.value.code_signing_flag}"
    email_protection_flag               = "${each.value.value.email_protection_flag}"
    enforce_hostnames                   = "${each.value.value.enforce_hostnames}"
    generate_lease                      = "${each.value.value.generate_lease}"
    key_bits                            = "${each.value.value.key_bits}"
    key_type                            = "${each.value.value.key_type}"
    key_usage                           = "${each.value.value.key_usage}"
    ext_key_usage                       = "${each.value.value.ext_key_usage}"
    no_store                            = "${each.value.value.no_store}"
    require_cn                          = "${each.value.value.require_cn}"
    ttl                                 = "${each.value.value.ttl}"
    use_csr_common_name                 = "${each.value.value.use_csr_common_name}"
    organization                        = "${each.value.value.organization}"
    country                             = "${each.value.value.country}"
    locality                            = "${each.value.value.locality}"
    ou                                  = "${each.value.value.ou}"
    postal_code                         = "${each.value.value.postal_code}"
    province                            = "${each.value.value.province}"
    street_address                      = "${each.value.value.street_address}"
}
