- name: Add the br_netfilter module
  community.general.modprobe:
    name: br_netfilter
    state: present

- name: SET SYSCTLS.
  ansible.posix.sysctl:
    name: net.ipv4.ip_forward
    value: '1'
    state: present