---
- name: Create and apply manifests for Nginx Routers
  hosts: masters
  tasks:
    - name: SETUP COMPONENTS.
      block:
        - name: SETUP K8S CONTROL-PLANE COMPONENTS.
          import_role:
            name: k8s
            tasks_from: k8s-control-plane-components.yaml
          tags:
            - control_plane
