kube_controller_manager_args:
    
    
    - --bind-address=0.0.0.0
    - --secure-port=10257
    - --allocate-node-cidrs=true
    - --cluster-cidr='{{ cluster_default_service_network }}'
    - --cluster-name=kubernetes
    - --concurrent-deployment-syncs=5
    - --concurrent-endpoint-syncs=5
    - --concurrent-namespace-syncs=10
    - --concurrent-replicaset-syncs=20
    - --concurrent-resource-quota-syncs=5
    - --deployment-controller-sync-period=30s
    - --horizontal-pod-autoscaler-sync-period=30s
    - --kube-api-burst=120
    - --kube-api-qps=100
    - --leader-elect=true
    - --leader-elect-lease-duration=15s
    - --leader-elect-renew-deadline=10s
    - --leader-elect-retry-period=2s
    - --namespace-sync-period=2m0s
    - --node-cidr-mask-size='{{ cluster_default_network_hostprefix }}'
    - --node-monitor-grace-period=40s
    - --node-monitor-period=5s
    - --node-startup-grace-period=1m0s
    - --pod-eviction-timeout=30s
    - --profiling=false
    - --resource-quota-sync-period=5m0s
    - --terminated-pod-gc-threshold=0
    - --use-service-account-credentials=true
    - --controllers=*,bootstrapsigner,tokencleaner,cloud-node-lifecycle
    - --authorization-always-allow-paths=/healthz,/metrics
    - --feature-gates=RotateKubeletServerCertificate=true
    - --v=2