etcd_args:
  - --trusted-ca-file={{ pki_path_ca }}/etcd-ca.pem
  - --cert-file={{ pki_path_certs }}/{{ k8s_component }}/system:etcd-server.pem
  - --key-file={{ pki_path_certs }}/{{ k8s_component }}/system:etcd-server-key.pem
  - --peer-trusted-ca-file={{ pki_path_ca }}/etcd-ca.pem
  - --peer-cert-file={{ pki_path_certs }}/{{ k8s_component }}/system:etcd-peer.pem
  - --peer-key-file={{ pki_path_certs }}/{{ k8s_component }}/system:etcd-peer-key.pem
  - --name={{ inventory_hostname }}
  - --client-cert-auth=true
  - --initial-advertise-peer-urls=https://{{ ansible_default_ipv4.address }}:2380
  - --listen-client-urls=https://{{ ansible_default_ipv4.address }}:2379,https://127.0.0.1:2379,https://127.0.1.1:2379
  - --listen-peer-urls=https://{{ ansible_default_ipv4.address }}:2380,https://127.0.0.1:2380,https://127.0.1.1:2380
  - --listen-metrics-urls=http://{{ ansible_default_ipv4.address }}:2381,https://127.0.0.1:2381,https://127.0.1.1:2381
  - --advertise-client-urls=https://{{ inventory_hostname }}:2379
  - --initial-cluster-token=etcd
  - --initial-cluster={{ groups.masters[0] }}=https://{{ hostvars[groups.masters[0]].ansible_default_ipv4.address }}:2380,{{ groups.masters[1] }}=https://{{ hostvars[groups.masters[1]].ansible_default_ipv4.address }}:2380,{{ groups.masters[2] }}=https://{{ hostvars[groups.masters[2]].ansible_default_ipv4.address }}:2380
  - --initial-cluster-state=new
  - --data-dir={{ etcd_data_dir }}
  - --strict-reconfig-check
  - --peer-client-cert-auth=true
  - --peer-auto-tls=true