---
- name: COPY CONFIGS.
  vars:
    dest_path: "{{ config.path | default(default_path_kubernetes) }}/{{ k8s_component }}/{{ config.name.split('.j2')[0] }}"
  ansible.builtin.template:
    src: "configs/{{ config.folder | default('') }}/{{ config.name }}"
    dest: '{{ config.path_abs | default(dest_path) }}'
    owner: root
    group: root
    mode: '664'
  loop: "{{ configs_in_copy }}"
  loop_control:
      loop_var: config
