- name: Create a directory if it does not exist
  ansible.builtin.file:
    path: "{{ k8s_component_path }}"
    state: directory
    mode: '0775'
  loop: "{{ basic_dirs }}"
  loop_control:
      loop_var: k8s_component_path
  tags:
    - update_dirs

- name: DOWNLOAD <cfssl>.
  get_url:
    url: "{{ k8s_cp_component_bin.url }}"
    dest: "{{ k8s_cp_component_bin.path }}"
    mode: 0775
  loop:
    - url: https://github.com/cloudflare/cfssl/releases/download/v{{ cfssl_version }}/cfssl_{{ cfssl_version }}_linux_amd64
      path: /usr/bin/cfssl
    - url: https://github.com/cloudflare/cfssl/releases/download/v{{ cfssl_version }}/cfssljson_{{ cfssl_version }}_linux_amd64
      path: /usr/bin/cfssljson
  loop_control:
      loop_var: k8s_cp_component_bin
