- block:
    - name: Create a directory if it does not exist
      vars:
        data_plane_basic_dirs:
          - /etc/cni/net.d
          - /opt/cni/bin
        all_dirs: "{{ data_plane_basic_dirs }}"
      ansible.builtin.file:
        path: "{{ k8s_component_path }}"
        state: directory
        mode: '0775'
      loop: "{{ all_dirs }}"
      loop_control:
          loop_var: k8s_component_path

    - name: DOWNLOAD BASIC TAR K8S-COMPONENTS.
      ansible.builtin.unarchive:
        src: "{{ k8s_component_tar.url }}"
        dest: "{{ k8s_component_tar.path }}"
        remote_src: yes
      loop:
        - url: https://github.com/containernetworking/plugins/releases/download/v{{ cni_plugin }}/cni-plugins-linux-amd64-v{{ cni_plugin }}.tgz
          path: /opt/cni/bin/
      loop_control:
          loop_var: k8s_component_tar

    - name: COPY BASIC CNI CONFIG.
      ansible.builtin.template:
        src: configs/cni-plugin/basic/99-loopback.conf
        dest: /etc/cni/net.d/99-loopback.conf
        owner: root
        group: root
        mode: '0775'
